### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by grvknight** [google-developer-training/android-basics-kotlin-bus-schedule-app#63] opened 2022-08-25 16:20 UTC
"FullScheduleFragmentDirections" showing error as Unresolved reference 

and " .navigate(action)" as Overload resolution ambiguity 

But the project builds successfully.

**Comment by osuleymanova** [comment] 2022-09-20 22:09
@grvknight 
Please provide the required details (codelab URL, step, visual proof of the error message... )while reporting an issue so that we can help you with troubleshooting.

**Comment by osuleymanova** [comment] 2023-01-11 18:29
The issue is closed as no further clarification of it was provided.

**Closed as completed by osuleymanova** 2023-01-11 18:29 UTC
