### ISSUE TITLE
Android Basics: Introduction to Room and Flow

### ISSUE THREAD

**Issue by sammorton11** [google-developer-training/android-basics-kotlin-bus-schedule-app#62] opened 2022-07-07 23:46 UTC
lifecycle.coroutineScope.launch {
            viewModel.scheduleForStopName(stopName).collect() {
                busStopAdapter.submitList(it)
            }
        }

this doesn't work

**Comment by RomanRC99** [comment] 2022-07-12 19:14
import kotlinx.coroutines.flow.collect

**Comment by osuleymanova** [comment] 2023-01-11 20:02
Duplicate of #59, #45

**Closed as completed** 2024-01-11 21:33 UTC
